<?php

namespace Vadiktok\DiscountBundle\Repository;

/**
 * BlockedIPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockedIPRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive($date, $IP = NULL)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.access >= :date');
        if (!empty($IP)) {
            $q
                ->andWhere('e.IP = :IP')
                ->setParameter('IP', $IP);
        }
        $result = $q->setParameter('date', $date)
            ->getQuery()
            ->getResult();
        return !empty($result) && is_array($result) ? count($result) : 0;
    }

    public function findInactive($date)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.access < :date')
            ->setParameter('date', $date)
            ->getQuery();

        return $q->getResult();
    }
}
